# Copyright (C) 2010 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/zte/arthur/extract-files.sh - DO NOT EDIT

# All the blobs necessary for warp
PRODUCT_COPY_FILES += \
    vendor/zte/arthur/proprietary/libEGL_adreno200.so:system/lib/egl/libEGL_adreno200.so \
    vendor/zte/arthur/proprietary/libGLESv2_adreno200.so:system/lib/egl/libGLESv2_adreno200.so \
    vendor/zte/arthur/proprietary/libGLESv1_CM_adreno200.so:system/lib/egl/libGLESv1_CM_adreno200.so \
    vendor/zte/arthur/proprietary/libq3dtools_adreno200.so:system/lib/egl/libq3dtools_adreno200.so \
    vendor/zte/arthur/proprietary/libgsl.so:system/lib/libgsl.so \
    vendor/zte/arthur/proprietary/yamato_pfp.fw:system/etc/firmware/yamato_pfp.fw \
    vendor/zte/arthur/proprietary/yamato_pm4.fw:system/etc/firmware/yamato_pm4.fw \
    vendor/zte/arthur/proprietary/qmuxd:system/bin/qmuxd \
    vendor/zte/arthur/proprietary/akmd2:system/bin/akmd2 \
    vendor/zte/arthur/proprietary/libril.so:system/lib/libril.so \
    vendor/zte/arthur/proprietary/libril-qc-qmi-1.so:system/lib/libril-qc-qmi-1.so \
    vendor/zte/arthur/proprietary/libril-qc-1.so:system/lib/libril-qc-1.so \
    vendor/zte/arthur/proprietary/libril-qcril-hook-oem.so:system/lib/libril-qcril-hook-oem.so \
    vendor/zte/arthur/proprietary/libdiag.so:system/lib/libdiag.so \
    vendor/zte/arthur/proprietary/init.qcom.bt.sh:system/etc/init.qcom.bt.sh \
    vendor/zte/arthur/proprietary/liboncrpc.so:system/lib/liboncrpc.so \
    vendor/zte/arthur/proprietary/libqmi.so:system/lib/libqmi.so \
    vendor/zte/arthur/proprietary/libdsm.so:system/lib/libdsm.so \
    vendor/zte/arthur/proprietary/libqueue.so:system/lib/libqueue.so \
    vendor/zte/arthur/proprietary/libdl.so:system/lib/libdl.so \
    vendor/zte/arthur/proprietary/libcm.so:system/lib/libcm.so \
    vendor/zte/arthur/proprietary/libmmgsdilib.so:system/lib/libmmgsdilib.so \
    vendor/zte/arthur/proprietary/libgsdi_exp.so:system/lib/libgsdi_exp.so \
    vendor/zte/arthur/proprietary/libgstk_exp.so:system/lib/libgstk_exp.so \
    vendor/zte/arthur/proprietary/libwms.so:system/lib/libwms.so \
    vendor/zte/arthur/proprietary/libnv.so:system/lib/libnv.so \
    vendor/zte/arthur/proprietary/libwmsts.so:system/lib/libwmsts.so \
    vendor/zte/arthur/proprietary/libpbmlib.so:system/lib/libpbmlib.so \
    vendor/zte/arthur/proprietary/libdss.so:system/lib/libdss.so \
    vendor/zte/arthur/proprietary/libauth.so:system/lib/libauth.so \
    vendor/zte/arthur/proprietary/libgemini.so:system/lib/libgemini.so \
    vendor/zte/arthur/proprietary/libgemini.so:obj/lib/libgemini.so \
    vendor/zte/arthur/proprietary/liboemcamera.so:system/lib/liboemcamera.so \
    vendor/zte/arthur/proprietary/liboemcamera.so:obj/lib/liboemcamera.so \
    vendor/zte/arthur/proprietary/libmmjpeg.so:system/lib/libmmjpeg.so \
    vendor/zte/arthur/proprietary/libmmipl.so:system/lib/libmmipl.so \
    vendor/zte/arthur/proprietary/hci_qcomm_init:system/bin/hci_qcomm_init \
    vendor/zte/arthur/proprietary/libOmxEvrcEnc.so:/system/lib/libOmxEvrcEnc.so \
    vendor/zte/arthur/proprietary/libOmxAacDec.so:/system/lib/libOmxAacDec.so \
    vendor/zte/arthur/proprietary/libOmxQcelp13Dec.so:/system/lib/libOmxQcelp13Dec.so \
    vendor/zte/arthur/proprietary/libOmxAmrEnc.so:/system/lib/libOmxAmrEnc.so \
    vendor/zte/arthur/proprietary/libOmxAdpcmDec.so:/system/lib/libOmxAdpcmDec.so \
    vendor/zte/arthur/proprietary/libOmxEvrcDec.so:/system/lib/libOmxEvrcDec.so \
    vendor/zte/arthur/proprietary/libOmxAmrDec.so:/system/lib/libOmxAmrDec.so \
    vendor/zte/arthur/proprietary/libOmxAmrwbDec.so:/system/lib/libOmxAmrwbDec.so \
    vendor/zte/arthur/proprietary/libOmxWmaDec.so:/system/lib/libOmxWmaDec.so \
    vendor/zte/arthur/proprietary/libOmxQcelp13Enc.so:/system/lib/libOmxQcelp13Enc.so \
    vendor/zte/arthur/proprietary/libOmxQcelpHwDec.so:/system/lib/libOmxQcelpHwDec.so \
    vendor/zte/arthur/proprietary/libOmxMp3Dec.so:/system/lib/libOmxMp3Dec.so \
    vendor/zte/arthur/proprietary/libOmxVdec.so:/system/lib/libOmxVdec.so \
    vendor/zte/arthur/proprietary/libOmxVenc.so:/system/lib/libOmxVenc.so \
    vendor/zte/arthur/proprietary/libOmxAmrRtpDec.so:/system/lib/libOmxAmrRtpDec.so \
    vendor/zte/arthur/proprietary/libOmxAacEnc.so:/system/lib/libOmxAacEnc.so \
    vendor/zte/arthur/proprietary/libomx_aacdec_sharedlibrary.so:system/lib/libomx_aacdec_sharedlibrary.so \
    vendor/zte/arthur/proprietary/libomx_amrdec_sharedlibrary.so:system/lib/libomx_amrdec_sharedlibrary.so \
    vendor/zte/arthur/proprietary/libomx_amrenc_sharedlibrary.so:system/lib/libomx_amrenc_sharedlibrary.so \
    vendor/zte/arthur/proprietary/libomx_avcdec_sharedlibrary.so:system/lib/libomx_avcdec_sharedlibrary.so \
    vendor/zte/arthur/proprietary/libomx_m4vdec_sharedlibrary.so:system/lib/libomx_m4vdec_sharedlibrary.so \
    vendor/zte/arthur/proprietary/libomx_mp3dec_sharedlibrary.so:system/lib/libomx_mp3dec_sharedlibrary.so \
    vendor/zte/arthur/proprietary/libomx_sharedlibrary.so:system/lib/libomx_sharedlibrary.so \
    vendor/zte/arthur/proprietary/libloc_ext.so:system/lib/libloc_ext.so \
    vendor/zte/arthur/proprietary/libloc_ext.so:obj/lib/libloc_ext.so \
    vendor/zte/arthur/proprietary/libril.so:obj/lib/libril.so \
    vendor/zte/arthur/proprietary/libloc-rpc.so:system/lib/libloc-rpc.so \
    vendor/zte/arthur/proprietary/libloc_api-rpc-qc.so:system/lib/libloc_api-rpc-qc.so \
    vendor/zte/arthur/proprietary/libcommondefs.so:system/lib/libcommondefs.so
